# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lidar_review_tools',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/lidar_review_tools',
                'lib_path': 'lidar_review_tools'},
  'syms': {'lidar_review_tools.core': {'lidar_review_tools.core.foo': ('core.html#foo', 'lidar_review_tools/core.py')}}}
