# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/ww_bokeh.ipynb.

# %% auto 0
__all__ = ['nb_output', 'ww_figure']

# %% ../nbs/ww_bokeh.ipynb 3
from bokeh.plotting import figure, show
from bokeh.io       import output_notebook

# %% ../nbs/ww_bokeh.ipynb 4
nb_output = False

# %% ../nbs/ww_bokeh.ipynb 5
def ww_figure(
  width=700,     # Width of plot output (pixels)
  height=400     # Height of plot output (pixels)
):
  """
  
  """
  global nb_output
  class WW_BKP():
    pass
  if nb_output == False:
    output_notebook()
    nb_output = True
  p = WW_BKP()
  p.width  = width
  p.height = height
  p.fig = figure( width = width, height = height)
  return p
